name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          pip install mkdocs==1.4.3 mkdocs-material==9.5.31 pillow cairosvg
      
      - name: Build and Deploy
        run: mkdocs gh-deploy --force

